#!/usr/bin/perl

##################
#
#  Check the network traffic on a Linux host
#
#  Usage:   check_net_traffic -d eth0 -x rx
#
#  Copyright (C) 2025 Bernd Arnold
#  https://github.com/wopfel/monitoring-plugins
#
#  Required modules:
#  - Getopt::Long (for command line option parsing)
#
##################

use strict;
use warnings;
use Getopt::Long;

# Sub routines
sub print_help();

my $opt_device;
my $opt_verbose;
#my $opt_warn;
my $opt_help;

my $answer = "";
my $crit_count = 0;
my $warn_count = 0;
my $status = "Unknown";
my @perfdata = ();
my @additional = ();


# Process command line options
GetOptions( "d|device=s"         => \$opt_device,
            "v|verbose"          => \$opt_verbose,
#            "w|warn=s"           => \$opt_warn,
            "help"               => \$opt_help,
)
    or do { print STDERR "Error in command line argument processing. Try '$0 -help'.\n"; exit 1; };

if ( $opt_help ) {
    print_help();
    exit 10;  # Outside of the official monitoring plugin's exit codes
}

if ( $opt_device !~ /^eth\d+$/ ) {
    print STDERR "Invalid device '$opt_device'. Must match 'eth0' for example.\n";
    exit 1;
}


###


my %time_series = ();

# Get the net values 2 times for measuring the difference
for my $iteration ( 0, 1 ) {

    for my $dir ( qw/ tx rx / ) {
        my $stat_filename = "/sys/class/net/$opt_device/statistics/${dir}_bytes";
        print "Using file '$stat_filename'.\n"  if  $opt_verbose;
        open FILE, "<", $stat_filename  or  die "Error: Cannot open file '$stat_filename'.";
	$time_series{ $dir }{ $iteration } = <FILE>;
        close FILE  or  die "Error: Cannot close file '$stat_filename'.";
    }

    # Sleep some seconds between iterations
    sleep 5  if  $iteration == 0;

}

my $diff_rx = $time_series{'rx'}{1} - $time_series{'rx'}{0};
my $diff_tx = $time_series{'tx'}{1} - $time_series{'tx'}{0};

my $diff_per_second_rx = $diff_rx / 5;
my $diff_per_second_tx = $diff_tx / 5;

$answer .= "$opt_device: ";
$answer .= sprintf "%.2f kB/sec in, ", $diff_per_second_rx/1000;
$answer .= sprintf "%.2f kB/sec out. ", $diff_per_second_tx/1000;

push @perfdata, sprintf "traffic_rx=%.2fkB", $diff_per_second_rx/1000;
push @perfdata, sprintf "traffic_tx=%.2fkB", $diff_per_second_tx/1000;

###

if ( $crit_count ) {
    $status = "Critical";
} elsif ( $warn_count ) {
    $status = "Warning";
} else {
    $status = "Ok";
}

print "$status: ";
print "$answer\n";

print "| " . join(" ", @perfdata) . "\n"  if @perfdata;
print join("\n", @additional) . "\n"  if @additional;

exit 2 if $status eq "Critical";
exit 1 if $status eq "Warning";
exit 0 if $status eq "Ok";
exit 3; # 'Unknown' return code



# Sub routine
sub print_help() {

    print STDERR <<~"END"
    Check Linux network traffic.

    Usage: $0 -d DEV -x DIRECTION

    Example: $0 -d eth0 -x tx

    Parameters:

        -d, --device DEV    Check DEV network device (eth0 for example)
        -h, --help          Show this help text
        -v, --verbose       Verbose output (for debugging)

    END

}
