#!/bin/bash

# Monitoring plugin for Icinga etc.
# Checks, if the given parameter is a valid directory

# USAGE: /usr/local/bin/check_dir /directory-which-should-be/checked

# Quick-and-dirty

if [[ -z $1 ]] ; then
    echo UNKNOWN: No parameter given
    exit 3
fi


if [[ -d $1 ]] ; then
    echo OK: "$1" is a valid directory
    exit 0
fi

echo CRITICAL: "$1" is not a directory
exit 2
