#!/bin/bash

# Quick-and-dirty
# USAGE: /usr/local/bin/check_dir /directory-which-should-be/checked

if [[ -z $1 ]] ; then
    echo UNKNOWN: No parameter given
    exit 3
fi


if [[ -d $1 ]] ; then
    echo OK: "$1" is a valid directory
    exit 0
fi

echo CRITICAL: "$1" is not a directory
exit 2
